### ISSUE TITLE
[BUG] Definition file errors in Angular 12

### ISSUE THREAD

**Issue by uberspeck** [ng-web-apis/common#21]
# 🐞 Bug report

### Description

Upgrading to Angular 12 is causing definition file errors...

```
Error: node_modules/@ng-web-apis/common/tokens/network-information.d.ts:1:23 - error TS2688: Cannot find type definition file for 'network-information-types'.

1 /// <reference types="network-information-types" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@ng-web-apis/common/tokens/network-information.d.ts:3:58 - error TS2304: Cannot find name 'NetworkInformation'.

3 export declare const NETWORK_INFORMATION: InjectionToken<NetworkInformation | null>;
                                                           ~~~~~~~~~~~~~~~~~~
```

### Reproduction

1. Update to Angular 12 via the [recommended steps](https://update.angular.io/?l=3&v=11.0-12.0)
2. Watch the fireworks 😄 

### Versions

-   OS: MacOS BigSur
-   Browser: Chrome
-   Angular 12

**Comment by waterplea** [comment]
That's weird. Can you try removing `package_lock.json` and doing a fresh `npm i`?

**Comment by uberspeck** [comment]
That fixed it! Sorry for the false alarm!
