### ISSUE TITLE
Plans to support Angular 13 - No ngcc

### ISSUE THREAD

**Issue by prabh-62** [ng-web-apis/common#28]
# 🚀 Feature request

### Is your feature request related to a problem?
No

### Describe the solution you'd like
Republish library with Angular 13 as dependency. Currently, Angular CLI takes additional time to compile the library before starting an application
`...Compiling @ng-web-apis/common : es2015 as esm2015`

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by krokofant** [comment]
@waterplea Can I help speed this along? This is the last library in my workspace not yet published with Ivy support.
