### ISSUE TITLE
[BUG] Angular v. 10 - Cannot use namespace 'CSS' as a type.

### ISSUE THREAD

**Issue by tobang** [ng-web-apis/common#5]
# 🐞 Bug report

### Description

When building my project under Angular version I get the following error:

```
ERROR in node_modules/@ng-web-apis/common/tokens/css.d.ts:4:14 - error TS2709: Cannot use namespace 'CSS' as a type.
    
    4         CSS: CSS;
                   ~~~
    node_modules/@ng-web-apis/common/tokens/css.d.ts:7:42 - error TS2709: Cannot use namespace 'CSS' as a type.
    
    7 export declare const CSS: `InjectionToken<CSS>;
```

### Reproduction

Build project under Angular version 10

### Expected behavior

No error should be shown

### Versions

-   OS: Linux
-   Browser: Chrome
-   Angular 10

**Comment by waterplea** [comment]
It's an unexpected issue with TypeScript 3.9+. We will release a fix, in a meantime you can upvote this: https://github.com/microsoft/TypeScript/issues/39273

**Comment by MarsiBarsi** [comment]
Hi! Thank you for this issue

We released a tmp fix for the problem in https://github.com/ng-web-apis/common/pull/6.
Please, update to a package version v1.4.1 to use it with Angular 10
